import { Metadata } from "next";

import Link from "next/link";
import AppHeader from "@/components/app-header";
import AppFooter from "@/components/app-footer";
import AppBanner from "@/components/app-banner";
import ProjectsGrid from "./projects/components/ProjectsGrid";

export const metadata: Metadata = {
  title: "Khokon portfolio ",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main>
      <AppHeader></AppHeader>
      <AppBanner></AppBanner>
      <div className="container mx-auto">
        <ProjectsGrid />
        <div className="mt-10 sm:mt-15 flex justify-center">
          <div className="font-general-medium flex items-center px-6 py-3 rounded-lg shadow-lg hover:shadow-xl bg-indigo-500 hover:bg-indigo-600 focus:ring-1 focus:ring-indigo-900 text-white text-lg sm:text-xl duration-300">
            <Link href="/projects" aria-label="More Projects" passHref>
              More Projects
            </Link>
          </div>
        </div>
      </div>
      <AppFooter></AppFooter>
    </main>
  );
}
