import AppFooter from "@/components/app-footer";
import AppHeader from "@/components/app-header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "This one is our about page",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AppHeader />
      {children}
      <AppFooter />
    </>
  );
}
